#%RAML 1.0 DataType
type: object
displayName: Application
description: This is an application object
properties:
  id:
    type: integer
    displayName: Application Id
    description: This is the unique id of the application
  name:
    type: string
    displayName: Application Name
    description: This is the name of the application.
    minLength: 3
    maxLength: 50
  status:
    type: string
    displayName: Application Status
    description: This is the status of the application.
    enum: [Green, Yellow, Red]
