type:
  Component:
    type: object
    displayName: Application Component
    description: This is a component in an application
    properties:
      id: string
      componentType: string
      alerts:
        type: array
