#%RAML 1.0 DataType
type: object
displayName: Incident Object
description: This object contains details of an incident
properties:
  id:
    type: string
    displayName: Incident Id
    description: Unique identifier for the Incident
    minLength: 3
    maxLength: 15
  typeId:
    type: string
    displayName: Incident Type Id
    description: Id of the incident type
  type:
    type: string
    displayName: Incident Type
    description: Type of the Incident
    enum: [Unavailability, Slowness]
  title:
    type: string
    displayName: Incident Title
    description: Title or short description of the incident
  details:
    type: string
    displayName: Incident Details
    description: Detailed description of the incident
  severity:
    type: string
    displayName: Incident Priority
    description: Priority of the Incident
    enum: [SEVERE,MEDIUM,MILD]
  createdDate:
    type: datetime-only
    displayName: Incident Created Date
    description: Date & Time the incident was created
  createdBy:
    type: string
    displayName: Incident Creator
    description: User/System creating the Incident
  lastUpdatedDate:
    type: datetime-only
    displayName: Incident Last Update Date
    description: Date & Time the incident was last updated
  lastUpdatedBy:
    type: string
    displayName: Incident Updator
    description: User/System last updated the Incident
  resolvedDate:
    type: datetime-only
    displayName: Incident Resolved Date
    description: Date & Time the incident was resolved
  assignedTo:
    type: string
    displayName: Incident Assignee
    description: User to which the incident is assigned to
  applicationId:
    type: string
    displayName: Aplication Id
    description: Aplication to which the incident is associated with
  applicationName:
    type: string
    displayName: Aplication Name
    description: Aplication name to which the incident is associated with
  componentId:
    type: string
    displayName: Component Id
    description: Component to which the incident is associated with
  componentName:
    type: string
    displayName: Component Name
    description: Component name to which the incident is associated with
