#%RAML 1.0
title: Facer
version: v1 - Sprint2
baseUri: http://api.facer.com
securitySchemes:
  basic: !include securitySchemes/basic.raml
types:
  User: !include resourceTypes/user.raml
  Error: !include resourceTypes/error.raml
  Application: !include resourceTypes/application.raml
  Event: !include resourceTypes/event.raml
  Comment: !include resourceTypes/comment.raml
  Incident: !include resourceTypes/incident.raml
  Component: !include resourceTypes/component.raml

/applications:
  displayName: Applications
  description: This service provides information about the applications in the system
  get:
    displayName: Get Applications
    description: Get applications based on the Query Parameters
    queryParameters:
      userId:
        type: string
        required: false
        minLength: 3
        maxLength: 15
    responses:
      200:
        description: This call retrieves list of applications based on the Query Parameters.
        body:
          application/json:
            type: Application[]
            example: !include examples/applications.json
      422:
        description: This is a application error
        body:
          application/json:
            type: Error
            example: !include examples/invalidUserError.json
/components:
  displayName: Components
  description: This resource provides access to the applciation components
  get:
    displayName: Get Components
    description: Get list of components based on the Query Parameters
    queryParameters:
      userId:
        type: string
        required: false
        minLength: 3
        maxLength: 15
      applicationId:
        type: string
        minLength: 3
        maxLength: 15
        required: false
    responses:
      200:
        description: This call retrieves list of components based on the Query Parameters.
        body:
          application/json:
            type: Component[]
            example: !include examples/components.json
      422:
        description: This is a application error
        body:
          application/json:
            type: Error
            example: !include examples/invalidApplicationError.json
/incidents:
  displayName: Incidents
  description: This service provides the information about the incidents in the system
  get:
    displayName: Get Incidents
    description: Gets list of incidents based on the Query Paramters
    queryParameters:
      userId:
        type: string
        required: false
        minLength: 3
        maxLength: 15
      applicationId:
        type: string
        minLength: 3
        maxLength: 15
        required: false
      componentId:
        type: string
        minLength: 3
        maxLength: 15
        required: false
    responses:
      200:
        description: This is the list of all incidents matching to the query criteria
        body:
          application/json:
            type: Incident[]
            example: !include examples/incidents.json
      422:
        description: This is a application error
        body:
          application/json:
            type: Error
            example: !include examples/invalidComponentError.json
  /{id}:
    displayName: Get Incident Details
    description: Get the details of an incident
    get:
      displayName: Get Incident Details
      description: This call gets the details of an incident based on id
      responses:
        200:
          description: This retrieves an alert details.
          body:
            application/json:
              type: Incident
              example: !include examples/incident.json
        422:
          description: This is a application error
          body:
            application/json:
              type: Error
              example: !include examples/invalidComponentError.json
    put:
      displayName: Update Incident
      description: This call updates the incident details
      body:
        application/json:
          type: Incident
      responses:
        200:
          description: This is a successful response of an alert update
          body:
            application/json:
              type: object
              properties:
                message: string
              example:
                {"message":"Incident updated successfully."}
        422:
          description: This is a application error
          body:
            application/json:
              type: Error
    delete:
      displayName: Delete Incident
      description: This call deletes the incident from the system
      responses:
        200:
          description: This is a successful response of incident deltion
        422:
          description: This is a application error
          body:
            application/json:
              type: Error
