type: Basic Authentication
describedBy:
  headers:
    Authorization:
      description: |
        The Authorization field value consists of credentials
        containing the authentication information of the user. Example "Authorization: Basic c2ViaXM6WipcbWokKEtcJlQnNGNZVlVkSHA="
